# python ../train.py --train_path ../../../data/input_representation/OPV_Min/augmentation/KFold/input_train_[0-9].csv --validation_path ../../../data/input_representation/OPV_Min/augmentation/KFold/input_valid_[0-9].csv --feature_names Augmented_SMILES --target_name calc_PCE_percent --model_type RF --hyperparameter_optimization True --hyperparameter_space_path ./opv_hpo_space.json --results_path ../../../training/OPV_Min/aug_SMILES --random_state 22

# python ../train.py --train_path ../../../data/input_representation/OPV_Min/augmentation/KFold/input_train_[0-9].csv --validation_path ../../../data/input_representation/OPV_Min/augmentation/KFold/input_valid_[0-9].csv --feature_names Augmented_SMILES --target_name calc_PCE_percent --model_type BRT --hyperparameter_optimization True --hyperparameter_space_path ./opv_hpo_space.json --results_path ../../../training/OPV_Min/aug_SMILES --random_state 22

python ../train.py --train_path ../../../data/input_representation/OPV_Min/augmentation/KFold/input_train_[0-9].csv --validation_path ../../../data/input_representation/OPV_Min/augmentation/KFold/input_valid_[0-9].csv --feature_names Augmented_SMILES --target_name calc_PCE_percent --model_type SVM --hyperparameter_optimization True --hyperparameter_space_path ./opv_hpo_space.json --results_path ../../../training/OPV_Min/aug_SMILES --random_state 22

# python ../train.py --train_path ../../../data/input_representation/OPV_Min/BRICS/KFold/input_train_[0-9].csv --validation_path ../../../data/input_representation/OPV_Min/BRICS/KFold/input_valid_[0-9].csv --feature_names DA_pair_BRICS --target_name calc_PCE_percent --model_type SVM --hyperparameter_optimization True --hyperparameter_space_path ./opv_hpo_space.json --results_path ../../../training/OPV_Min/BRICS --random_state 22

# python ../train.py --train_path ../../../data/input_representation/OPV_Min/fingerprint/KFold/input_train_[0-9].csv --validation_path ../../../data/input_representation/OPV_Min/fingerprint/KFold/input_valid_[0-9].csv --feature_names DA_FP_radius_3_nbits_512 --target_name calc_PCE_percent --model_type SVM --hyperparameter_optimization True --hyperparameter_space_path ./opv_hpo_space.json --results_path ../../../training/OPV_Min/fingerprint --random_state 22

# python ../train.py --train_path ../../../data/input_representation/OPV_Min/manual_frag/KFold/input_train_[0-9].csv --validation_path ../../../data/input_representation/OPV_Min/manual_frag/KFold/input_valid_[0-9].csv --feature_names DA_manual --target_name calc_PCE_percent --model_type SVM --hyperparameter_optimization True --hyperparameter_space_path ./opv_hpo_space.json --results_path ../../../training/OPV_Min/manual_frag --random_state 22

python ../train.py --train_path ../../../data/input_representation/OPV_Min/manual_frag/KFold/input_train_[0-9].csv --validation_path ../../../data/input_representation/OPV_Min/manual_frag/KFold/input_valid_[0-9].csv --feature_names DA_manual_aug --target_name calc_PCE_percent --model_type RF --hyperparameter_optimization True --hyperparameter_space_path ./opv_hpo_space.json --results_path ../../../training/OPV_Min/manual_frag_aug --random_state 22

python ../train.py --train_path ../../../data/input_representation/OPV_Min/manual_frag/KFold/input_train_[0-9].csv --validation_path ../../../data/input_representation/OPV_Min/manual_frag/KFold/input_valid_[0-9].csv --feature_names DA_manual_aug --target_name calc_PCE_percent --model_type BRT --hyperparameter_optimization True --hyperparameter_space_path ./opv_hpo_space.json --results_path ../../../training/OPV_Min/manual_frag_aug --random_state 22

python ../train.py --train_path ../../../data/input_representation/OPV_Min/manual_frag/KFold/input_train_[0-9].csv --validation_path ../../../data/input_representation/OPV_Min/manual_frag/KFold/input_valid_[0-9].csv --feature_names DA_manual_aug --target_name calc_PCE_percent --model_type SVM --hyperparameter_optimization True --hyperparameter_space_path ./opv_hpo_space.json --results_path ../../../training/OPV_Min/manual_frag_aug --random_state 22

# python ../train.py --train_path ../../../data/input_representation/OPV_Min/SMILES/KFold/input_train_[0-9].csv --validation_path ../../../data/input_representation/OPV_Min/SMILES/KFold/input_valid_[0-9].csv --feature_names DA_SMILES --target_name calc_PCE_percent --model_type SVM --hyperparameter_optimization True --hyperparameter_space_path ./opv_hpo_space.json --results_path ../../../training/OPV_Min/SMILES --random_state 22

# python ../train.py --train_path ../../../data/input_representation/OPV_Min/SMILES/KFold/input_train_[0-9].csv --validation_path ../../../data/input_representation/OPV_Min/SMILES/KFold/input_valid_[0-9].csv --feature_names DA_SELFIES --target_name calc_PCE_percent --model_type SVM --hyperparameter_optimization True --hyperparameter_space_path ./opv_hpo_space.json --results_path ../../../training/OPV_Min/SELFIES --random_state 22

# python ../train.py --train_path ../../../data/input_representation/OPV_Min/SMILES/KFold/input_train_[0-9].csv --validation_path ../../../data/input_representation/OPV_Min/SMILES/KFold/input_valid_[0-9].csv --feature_names DA_BigSMILES --target_name calc_PCE_percent --model_type SVM --hyperparameter_optimization True --hyperparameter_space_path ./opv_hpo_space.json --results_path ../../../training/OPV_Min/BigSMILES --random_state 22
