wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.10
    framework: huggingface
    huggingface_version: 4.16.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.10
    start_time: 1646104394
    t:
      1:
      - 1
      - 5
      - 9
      - 11
      3:
      - 4
      - 16
      4: 3.8.10
      5: 0.12.10
      6: 4.16.2
      8:
      - 5
accelerator:
  desc: null
  value: dp
callbacks:
  desc: null
  value: false
dataloader_num_workers:
  desc: null
  value: 3
drop_prob:
  desc: null
  value: 0.3
enable_progress_bar:
  desc: null
  value: false
gpus:
  desc: null
  value: -1
learning_rate:
  desc: null
  value: 0.001
log_every_n_steps:
  desc: null
  value: 100
logger:
  desc: null
  value: <pytorch_lightning.loggers.wandb.WandbLogger object at 0x14d3ac214040>
max_epochs:
  desc: null
  value: 500
n_embedding:
  desc: null
  value: 256
n_hidden:
  desc: null
  value: 256
n_output:
  desc: null
  value: 1
test_batch_size:
  desc: null
  value: 32
train_batch_size:
  desc: null
  value: 128
val_batch_size:
  desc: null
  value: 32
